### ISSUE TITLE
how to handle this, thanks.

### ISSUE THREAD

**Issue by liamxg** [clifmckee/bat_CoV_review#1]
mammterr <- readOGR(dsn="./Data/MAMMALS_TERRESTRIAL_ONLY/MAMMALS_TERRESTRIAL_ONLY.shp")
Error in ogrListLayers(dsn = dsn) : Cannot open data source

**Comment by clifmckee** [comment]
I cannot share this data set because it is too large. I recommend that you download the files on your own local computer to run this code. The data can be found here: https://www.iucnredlist.org/resources/spatial-data-download. The data of interest are the Terrestrial Mammals: https://www.iucnredlist.org/resources/files/7864a4a2-f7ed-422f-8a43-7fc42e3883c9.

**Comment by liamxg** [comment]
.thanks,

**Comment by liamxg** [comment]
tree <- read.tree("./Data/bat_families.nwk"), could you please tell me where to find this file, thanks.

**Comment by clifmckee** [comment]
The repository has been updated with the files requested. They can be found in the "Data" folder.

**Comment by liamxg** [comment]
thanks.
