### ISSUE TITLE
no data for first 144 lines.

### ISSUE THREAD

**Issue by liamxg** [clifmckee/bat_CoV_review#2]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/46078579/158927570-ea53a165-d260-40d3-a534-19044a173462.png">

**Comment by liamxg** [comment]
for merged_CoV_spp in Bat_coronavirus_table.R script.

**Comment by clifmckee** [comment]
The white space was being imported with the CSV files for some reason. I updated those files and it fixed this issue. I also made some small changes to all the other scripts. New changes have been pushed to the repository.

**Comment by liamxg** [comment]
thanks

**Comment by liamxg** [comment]
you are so nice.

**Comment by liamxg** [comment]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/46078579/158935449-ca58a9ef-0a9e-4576-aa0f-a292ecce17c5.png">
how do you control the tree branch line and name are are the same level

**Comment by clifmckee** [comment]
It s controlled by line 112 of 'bat_sampling_summary_plots.R' `ggtree(tree) + ylim(-1.9, 26.2)`. The tree and the names look misaligned if you view the figure in R, but that is because the settings are currently optimized so that everything is aligned correctly when the plot is saved as a PDF or PNG outside of R. You can see the PNG version in the 'Results' folder is correct.

**Comment by liamxg** [comment]
thanks for your nice help.
